# 1. 文件路径
file_paths:
  satellite_path: "../data/himawari_nc/"
  crop_statellite_path: "../data/crop_himawari/"

# 2. 电站配置
stations:
  lat: 37.80
  lon: 112.50

# 3. 要处理的卫星图像
statellite:
  crop_size: 96  # 96x96 pixels

# 4. 要处理的时间
dates:
  start_date: "2020-01-27"
  end_date: "2020-01-27"

