# 1. 文件路径
file_paths:
  satellite_path: "../data/himawari_nc/"
  crop_statellite_path: "../data/crop_himawari/"
  aligned_satellite_path: "../data/crop_himawari/15min"

# 2. 电站配置
stations:
  lat: -23.75
  lon: 133.85

# 3. 要处理的卫星图像
statellite:
  crop_size: 96  # 96x96 pixels

# 4. 要处理的时间
dates:
  start_date: "2020-01-27"
  end_date: "2020-01-27"

